services:
  # PostgreSQL database
  db:
    image: postgres:15
    container_name: streamline-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: streamline_scheduler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Rust backend
  backend:
    build: .
    container_name: streamline-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/streamline_scheduler
      JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
      JWT_EXPIRY_HOURS: 24
      PORT: 3001
      RUST_LOG: info
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
