spring:
    application:
        name: streamline-sheduler
    jpa:
        properties:
            hibernate:
                globally_quoted_identifiers: true
        hibernate:
            ddl-auto: create
        database: postgresql
    datasource:
        url: jdbc:postgresql://localhost:5432/streamline_scheduler
        password: ${SPRING_DATASOURCE_PASSWORD}
    config:
        import:
        - optional:file:.env[.properties]
springdoc:
    default-produces-media-type: application/json
        

server:
    port: 8181
    servlet:
        context-path: /api/v1
